name: Prettier Check

on: 
  pull_request:
  push:
    branches:
      - main

jobs: 
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Run Prettier check
        run: yarn run format:check